### ISSUE TITLE
Scene colliders

### ISSUE THREAD

**Issue by Shatur** [Jondolf/bevy_xpbd#104]
Rapier have `AsyncSceneCollider` to automatically generate collision after scene spawn.
I would suggest to add a similar feature for convenience, but with the ability to specify collider layers.

**Comment by Jondolf** [comment]
Yeah I think this should be relatively straightforward to add. I think Rapier just waits until the mesh/scene is ready and then adds the collider.

However, I was wondering if it would be possible to generate colliders from meshes *in advance* once Assets V2 is ready. For convex decomposition, the VHACD algorithm that Parry uses is pretty expensive and can even take several minutes for large colliders, so ideally we would have a preprocessing step where colliders are generated at compile-time with configuration for things like detail.

I haven't taken a proper look at Assets V2 yet though so I don't know if this would even be possible or if it would require a cumbersome API, but it's worth considering. For now though we can just add normal async colliders, I'll add it on my todo list

**Comment by donkey-donkey** [comment]
> Rapier have `AsyncSceneCollider` to automatically generate collision after scene spawn. I would suggest to add a similar feature for convenience, but with the ability to specify collider layers.

Have you implemented any workarounds for the time being? Im using rapier's AsyncSceneCollider atm and we would love to try out xpbd.

**Comment by Jondolf** [comment]
> > Rapier have `AsyncSceneCollider` to automatically generate collision after scene spawn. I would suggest to add a similar feature for convenience, but with the ability to specify collider layers.
> 
> Have you implemented any workarounds for the time being? Im using rapier's AsyncSceneCollider atm and we would love to try out xpbd.

Not yet, but something lïke `AsyncSceneCollider` should be straightforward to add into your app even without forking the crate. You can basically copy Rapier's implementation by just adding an `AsyncSceneCollider` component and a system that initializes the actual colliders.

You can find `AsyncSceneCollider` [here](https://github.com/dimforge/bevy_rapier/blob/a149ff59933f26869482fa3797d1188afecde750/src/geometry/collider.rs#L27) and the system [here](https://github.com/dimforge/bevy_rapier/blob/a149ff59933f26869482fa3797d1188afecde750/src/plugin/systems.rs#L769). Instead of `Collider::from_bevy_mesh`, you can use `Collider::trimesh_from_bevy_mesh` or `Collider::convex_decomposition_from_bevy_mesh`.

For normal `AsyncCollider`s, you can find similar implementations.

**Comment by sphinxc0re** [comment]
Hey 👋🏼 firstly: Thank you for creating Avian ❤️ 

Should this be reopened? I wasn't able to find anything related to scenes in the documentation 🤔 

_(I was so excited to have a simple solution, but it wasn't meant to be 🥲)_
