### ISSUE TITLE
How do I make things fly ?

### ISSUE THREAD

**Issue by bestouff** [Jondolf/bevy_xpbd#106]
I'd like to grave some objects fly, i.e. I'd like to be able to compute their lift, drag, and have everything work like by magic.
Is that something possible ? If yes how would I do that ? 1-entity constraints ?

**Comment by Jondolf** [comment]
So you want to simulate aerodynamics, like a paper slowly falling or an airplane gliding? This is not built-in functionality, but it is technically possible, although quite difficult. Games tend to fake aerodynamics since it can be expensive and it can quickly become very complex. For example, if you had a plane controller, you could apply forces and torques to the plane depending on the wing flap orientation and the plane's velocity, and ignore the precise aerodynamics of each individual part of the plane.

There was also discussion about position-based aerodynamics on the Ten Minute Physics (one of the XPBD authors) Discord channel's questions-and-help channel a couple of weeks ago. You can find a link to the Discord [here](https://www.youtube.com/@TenMinutePhysics/about) (not sure if allowed to post direct link).

One of the people there has a 2D version working by forming rigid bodies from several individual particles, and computing lift/drag on a per-particle basis. I think they do something like this for every particle (in C#, not Rust):

```c#
float dotFactor = max(|v|^2 * dot(normal, vDir), 0);
float2 dampDelta = -vDir * dotFactor * dampFactor;
float2 liftDelta = Normal(vDir) * sign(Cross(normal, vDir))) * dotFactor * liftFactor;
// Apply deltas to rigid bodies via "Detailed Rigid Body Simulation with Extended Position-based Dynamics"'s
// positional constraints.
```

So yes, it's possible with constraints, but it requires quite a lot of work, and it might be easier to implement with a per-particle approach rather than a per-rigidbody approach. Another challenge here would be that you need to make the visual mesh match the particles somehow.

**Comment by bestouff** [comment]
Ok I get it.
Stupid newbie question: how do I apply forces on a body ?

**Comment by Jondolf** [comment]
You can use `ExternalForce` and `ExternalTorque` similar to Rapier. Here are the 3D docs for it: https://docs.rs/bevy_xpbd_3d/latest/bevy_xpbd_3d/components/struct.ExternalForce.html

**Comment by bestouff** [comment]
Ooh that's perfect. Thank you very much !
