### ISSUE TITLE
Add doc alias for "elasticity" for Restitution

### ISSUE THREAD

**Issue by alice-i-cecile** [Jondolf/bevy_xpbd#113]
Took a bit to find this, so a doc alias would be useful.

**Comment by Jondolf** [comment]
[Elasticity](https://en.wikipedia.org/wiki/Elasticity_(physics)) and [restitution](https://en.wikipedia.org/wiki/Coefficient_of_restitution) are technically two separate terms, although they are related in some ways.

**Elasticity** refers to the ability of a body to return to its original shape and size after deformation, while the **coefficient of restitution** refers to the ratio of the relative speeds of the bodies after and before collision, which essentially corresponds to how much kinetic energy dissipation occurred.

Of course, a bouncing ball is elastic since it returns to its original shape, which causes it to bounce. A more elastic ball typically bounces higher than an otherwise similar but less elastic ball. Elasticity affects what a contact's coefficient of restitution would be, but the terms are not synonymous.

The difference might be subtle enough that we can probably still add it as an alias though. I would also add "bounciness", since Unity uses that and Godot seems to use "bounce".

**Comment by alice-i-cecile** [comment]
That makes sense from a physics angle. I like doc alias-ing both bounciness and elasticity, but Restitution is definitely the best name for it.
