### ISSUE TITLE
Incorrect time dilation for custom fixed schedules.

### ISSUE THREAD

**Issue by starwolfy** [Jondolf/bevy_xpbd#124]
Configurations with their own fixed schedule passed to `PhysicsPlugins::new()` have incorrect time dilation.
In my case I pass Bevy's `FixedUpdate` schedule that I have configurated to run at `1./16.`. This causes physics sim to run in slow-motion. Setting `PhysicsTimestep::Fixed` in addition does not solve the time dilation problem.
I pass my own `FixedUpdate` to keep my [schedules in sync](https://docs.rs/bevy_xpbd_3d/latest/bevy_xpbd_3d/plugins/struct.PhysicsPlugins.html#custom-schedule).

**Comment by starwolfy** [comment]
Inside `src/plugins/setup.rs` at function `run_physics_schedule`: changing `delta_seconds` to `let delta_seconds = world.resource::<FixedTime>().period.as_secs_f32();` fixes it. [My fix.](https://github.com/starwolfy/bevy_xpbd/commit/59cabbe9e55fa9a114a78b9602483accb73319df)

It seems that you want to either check whether the plugin uses Bevy's `FixedUpdate` schedule or you want to add another configuration option that allows you to set your own fixed `delta_seconds`. Which of the two is better? If I have the time I could create a PR.

**Comment by Jondolf** [comment]
I'd say that we should check if the plugin uses `FixedUpdate`, and if it does, use `FixedTime` for `delta_seconds`. This way, it will "just work" if you have configured `FixedTime`.

Having a separate configuration option for the value that `delta_seconds` uses seems easily missable and error-prone for users in my opinion, since the physics timestep can already be configured through `PhysicsTimestep`.

**Comment by starwolfy** [comment]
@Jondolf My PR #128 has the fix with the implementation you favor.
