### ISSUE TITLE
Extremely slow debug code

### ISSUE THREAD

**Issue by volodalexey** [Jondolf/bevy_xpbd#131]
I am trying to replace `rapier` engine with `xpbd`.
Due to very similar syntax I switched from `rapier` to `xpbd` in just a few hours, awesome!
However I can not proceed with [my game](https://github.com/volodalexey/bevy-wasm-ball-shooter) development.
Debug mode `cargo run` extremely slow. `2` - `10` fps...
![2023-08-23_19-13](https://github.com/Jondolf/bevy_xpbd/assets/8973562/0659199b-5432-45e7-bb1d-00a21c2e1970)
7 balls  + 1 projectile ball + 2 next balls + 2 walls as cuboids + 2 lines as cuboids  = that is all
And even for this small amount of entities physics engine is extremely slow.
I am using simple colliders+positions, maybe I am missing something?
In comparison to `bevy_rapier` - I can run about 30 entities without any lags.

Is there any diagnostic for this engine, so at least I can try to investigate what system cause this?
I can only see that [comment out](https://github.com/volodalexey/bevy-wasm-ball-shooter/blob/main/src/gameplay/ball/grid_ball_bundle.rs#L39) `Collider` increase my frame rate to `20` fps...

Tips from [[Why is performance so bad?](https://docs.rs/bevy_xpbd_2d/latest/bevy_xpbd_2d/#why-is-performance-so-bad)](https://docs.rs/bevy_xpbd_2d/latest/bevy_xpbd_2d/#why-is-performance-so-bad) section do not help.

**Comment by Jondolf** [comment]
To some extent, it's expected that debug mode is over 100 times slower than release mode. [This is also the case for Rapier](https://rapier.rs/docs/user_guides/bevy_plugin/common_mistakes#my-local-build-of-rapier-is-slower-than-the-online-demos). 

You can optimize the debug mode using:

```toml
[profile.dev.package.bevy_xpbd_2d]
opt-level = 1
# or 2 or 3 depending on how much optimization you want
```

As for why bevy_rapier's debug mode is faster, I believe bevy_xpbd has a higher default substep count, which gives more accuracy at the cost of performance. Lowering it from 12 to something like 6 or 4 should already give better performance. bevy_xpbd also just hasn't had as much time for optimization yet since we're still missing some quite important features.

For investigating performance, you can use Tracy or flamegraph, see [Bevy's profiling docs](https://github.com/bevyengine/bevy/blob/main/docs/profiling.md). We also have a very simple Criterion benchmark for spawning a bunch of cubes, but that won't show how long individual systems take.

**Comment by volodalexey** [comment]
Thanks for reply.
I tried:
```toml
[profile.dev.package.bevy_xpbd_2d]
opt-level = 3
```
This is enoigh for development, I got `20` fps for `20` entities/colliders.
