### ISSUE TITLE
can you give a load_asset example?

### ISSUE THREAD

**Issue by lx2720** [Jondolf/bevy_xpbd#146]
Can you give me an example of loading a third-party model to generate collisions? I loaded a third-party model myself to generate collisions, which became very slow

**Comment by Jondolf** [comment]
What method are you currently using for generating the collider? Are you using `Collider::trimesh_from_bevy_mesh` or `Collider::convex_decomposition_from_bevy_mesh`? If the model is an asset like a gltf file, you'll need "async scene colliders" which aren't built-in yet, but you can implement them in your own app pretty easily, see #104 and #135.

Also, do you mean that generating the collider at the start of the app takes time, or that the performance is bad when objects are interacting with the collider? If you're using convex decomposition, it's expected that the initial load is very slow because of the underlying algorithm, but we might be able to fix this in the future using Bevy's asset rework.

**Comment by lx2720** [comment]
[world.txt](https://github.com/Jondolf/bevy_xpbd/files/12508786/world.txt)
Thank you very much for your reply! This is an. rs file. I put it in main, but I'm not very good at it. The rendering is fine, but the imported mesh did not collide, and the game runs very slowly. Can you help me take a look? Thank you again!

**Comment by lx2720** [comment]
i use Collider::trimesh_from_bevy_mesh

**Comment by lx2720** [comment]
Yesterday I saw a third-party gltf import example that you haven't uploaded, I take a look at that first?

**Comment by lx2720** [comment]
Yesterday I saw you have an example of a third-party gltf import that you are about to upload. Let me take a look at that first?

**Comment by lx2720** [comment]
> 

Gltf loads quickly, but runs slowly, almost stuck

**Comment by lx2720** [comment]
Another small issue is, if multiple third-party models need to be loaded during startup, their previous order cannot be guaranteed. Do I need to merge them into one load
