### ISSUE TITLE
Add `contacts` method to SpatialQuery

### ISSUE THREAD

**Issue by stargazing-dino** [Jondolf/bevy_xpbd#168]
Hi ! I'm trying to make my local fork of `bevy_mod_wanderlust` work with `bevy_xpbd` and one of the things that's tripping me up is that I can't find any direct parallel for `bevy_rapier3d::parry::query::contact`. `Bevy_mod_wanderlust` does some interesting iterative position adjusting in the case they're penetrating the ground already and relies on `contact` to know which direction to back out from:

```rs
if let Ok(Some(contact)) = bevy_rapier3d::parry::query::contact(
    &cast_iso,
    &*shape_caster.raw,
    &ground_iso,
    &*ground_collider.raw,
    0.0,
) {
    // Adjust position so we're no longer contacting
}
```

`bevy_xpbd` has a similar `SpatialQuery::shape_intersections` but it only returns an Entity. I think I could align the entities with the Contacts in the physics world or something but I think they'd be out of date with those from the shape_intersections if you we're to run it multiple times in one frame meanwhile adjusting positions right? That's just my assumption, I'm not sure.

### Edit (I'm dumb)

`shape_intersections` I think still should return Contacts but that function isn't what `bevy_rapier3d::parry::query::contact` does. `shape_intersections` returns all entities colliding with that one specific shape. Instead, I think it'd be better to ask for a function to be added to SpatialQuery that returns the contact points between two colliders given their isometries? I might be able to PR this if you'd prefer.

Anyways, very much enjoying the library :D

**Comment by Jondolf** [comment]
Hi! We should definitely add a `contact` equivalent. I'm not sure if `SpatialQuery` is the right place though since `contact` is just a utility function that doesn't require any external state; maybe we should make it a public function?

I'm thinking that we could have `contact` (returns `ContactData`, equivalent to Parry's [`contact`](https://docs.rs/parry3d/latest/parry3d/query/contact/fn.contact.html)) and `contact_manifolds` (returns `Contacts`, equivalent to Parry's [`PersistentQueryDispatcher::contact_manifolds`](https://docs.rs/parry3d/latest/parry3d/query/trait.PersistentQueryDispatcher.html#tymethod.contact_manifolds)). We could add a separate `query` module for these utils under `narrow_phase`, and later on we could add more utils like `time_of_impact`, `closest_points` etc.

I can probably make a PR for this today

**Comment by Jondolf** [comment]
I made a draft PR to add APIs for these contact queries (and more). It only has `contact` and `contact_manifolds` currently, but I'll work on it more today and add the remaining contact queries and docs

**Comment by Jondolf** [comment]
The PR should be done now! I added pretty much all of Parry's queries (`contact`, `contact_manifolds`, `closest_points`, `distance`, `intersection_test` and `time_of_impact`) along with some nice docs and code examples.

I'll probably merge it tomorrow evening unless there's something you'd like to change

**Comment by stargazing-dino** [comment]
Woot ! Much appreciated !

I'll pull down your PR and play around with it a bit today and let you know if I find anything but from a cursory glance, everything looks well thought out.
