### ISSUE TITLE
Way to disable debug render for TriMesh colliders

### ISSUE THREAD

**Issue by LeshaInc** [Jondolf/bevy_xpbd#75]
Static level geometry is often expressed in TriMesh colliders. When the level is big, debug render tries to draw millions of lines using an immediate mode API, which is painfully slow (10 fps)

Other solutions include:
 - drawing a wireframe mesh instead of Gizmos
 - frustum culling
 - per-entity opt-in or opt-out of debug rendering

**Comment by Jondolf** [comment]
The per-entity configuration is already possible using `DebugRender` and `without_collider`. I also made a new PR #76 that makes the API nicer so you can even do `DebugRender::none()` to disable all debug features for that entity.

Later on it would definitely be nice to use meshes for the colliders instead of gizmos, as it would also make it possible to optionally render colliders as solid (not wireframes), which I recall someone asking for a while ago regarding Rapier.
